spring:
  application:
    name: sos-ambulance-service
  profiles:
    active: ${SPRING_PROFILE:dev}

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
