spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medibridge_sos_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Prakash@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: OmprakashreddySaggam@gmail.com
    password: frgizhomwrdyatoe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  health:
    mail:
      enabled: false

websocket:
  allowed-origins: http://localhost:3000,http://localhost:4200

logging:
  level:
    root: INFO
    com.medibridge: DEBUG
